### ISSUE TITLE
可以支持添加多个账号吗？

### ISSUE THREAD

**Issue by Reiice** [nice2cu1/lixianla#2]

**Comment by Reiice** [comment]
我不会写代码 😭 暂时利用docker满足了同时部署多个账号，但属于本末倒置了 😅 
作者可否考虑在 [`main.py`](https://github.com/nice2cu1/lixianla/blob/master/main.py) 支持添加多个账号？非常感谢

**Comment by nice2cu1** [comment]
已更新，使用[user.json](https://github.com/nice2cu1/lixianla/blob/master/user.json)填入相关数据。
