### ISSUE TITLE
签到验证码报错循环

### ISSUE THREAD

**Issue by Reiice** [nice2cu1/lixianla#3]
```log
...

签到验证码：13248
sign_response_bs.find(id='body').text.strip() ======== 验证码错误!!!
签到出错：验证码错误!!!,将在1s后重试
count = 验证码错误!!!
msg = 0

...
```
附cron生成log
[py.log](https://github.com/nice2cu1/lixianla/files/10827394/py.log)

**Comment by Reiice** [comment]
我刚刚又看了一遍log发现 1503 行第一个号是成功了的XD
但是这试错的次数...

**Comment by nice2cu1** [comment]
找个时间我重写一下吧，这两天考试，没多少时间，多账号我只简单试了一下，没有做太多测试。

**Comment by Reiice** [comment]
应该是我这台环境的问题，用另一台跑了两天都没问题
